# fly.toml app configuration file generated for jokes-ai on 2023-05-22T16:18:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jokes-ai"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
